# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74c39cc36db742b78108b0d78d93397f9a2b9a9e778fcb89a601f632a56ad0946f5530839fcb8ae24ede1fca5a0ed72dd1ae3a0ae65ec9dba3cda0e27ca0982

test:
  secret_key_base: 2b9182696ebab9d34e30e4ed8c765e9c77a5954a4113a32457fa7c2d2ab98d84767ceb40dec3e9652191045e542217d7d1aaba642c0ff0e55a25bc4fd9d5220b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
